// ============================================================================
// Component Catalog — 46 Radix UI components organized in 7 categories
// ============================================================================

import type { ComponentMetadata, ComponentCategory } from "../types/ComponentMetadata";

export const COMPONENT_CATALOG: ComponentMetadata[] = [
  // ========== Entrada (6) ==========
  {
    componentType: "Button",
    category: "Entrada",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "children",
        label: "Texto",
        type: "text",
        defaultValue: "Button",
        supportsTemplates: true,
      },
      {
        name: "variant",
        label: "Variante",
        type: "select",
        defaultValue: "default",
        options: [
          { value: "default", label: "Default" },
          { value: "destructive", label: "Destructive" },
          { value: "outline", label: "Outline" },
          { value: "ghost", label: "Ghost" },
        ],
      },
    ],
  },
  {
    componentType: "Input",
    category: "Entrada",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "placeholder",
        label: "Placeholder",
        type: "text",
        defaultValue: "Digite...",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Textarea",
    category: "Entrada",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    propFields: [
      {
        name: "placeholder",
        label: "Placeholder",
        type: "text",
        defaultValue: "Digite...",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Checkbox",
    category: "Entrada",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "label",
        label: "Label",
        type: "text",
        defaultValue: "Checkbox",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "RadioGroup",
    category: "Entrada",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    propFields: [
      {
        name: "label",
        label: "Label",
        type: "text",
        defaultValue: "Radio Group",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "ToggleGroup",
    category: "Entrada",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    propFields: [],
  },

  // ========== Seleção (3) ==========
  {
    componentType: "Select",
    category: "Seleção",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "placeholder",
        label: "Placeholder",
        type: "text",
        defaultValue: "Selecionar...",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "DropdownMenu",
    category: "Seleção",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Toggle",
    category: "Seleção",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },

  // ========== Feedback (7) ==========
  {
    componentType: "Alert",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 2,
    propFields: [
      {
        name: "title",
        label: "Título",
        type: "text",
        defaultValue: "Alert",
        supportsTemplates: true,
      },
      {
        name: "description",
        label: "Descrição",
        type: "text",
        defaultValue: "This is an alert",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Badge",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "children",
        label: "Texto",
        type: "text",
        defaultValue: "Badge",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Progress",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "value",
        label: "Valor",
        type: "number",
        defaultValue: 50,
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Skeleton",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Tooltip",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "content",
        label: "Conteúdo",
        type: "text",
        defaultValue: "Tooltip content",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "HoverCard",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    propFields: [
      {
        name: "content",
        label: "Conteúdo",
        type: "text",
        defaultValue: "Hover card content",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Sonner",
    category: "Feedback",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "message",
        label: "Mensagem",
        type: "text",
        defaultValue: "Toast message",
        supportsTemplates: true,
      },
    ],
  },

  // ========== Layouts (5) ==========
  {
    componentType: "Card",
    category: "Layouts",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 3,
    propFields: [
      {
        name: "title",
        label: "Título",
        type: "text",
        defaultValue: "Card Title",
        supportsTemplates: true,
      },
      {
        name: "description",
        label: "Descrição",
        type: "text",
        defaultValue: "Card description",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Dialog",
    category: "Layouts",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "title",
        label: "Título",
        type: "text",
        defaultValue: "Dialog",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Drawer",
    category: "Layouts",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Sheet",
    category: "Layouts",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Popover",
    category: "Layouts",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "content",
        label: "Conteúdo",
        type: "text",
        defaultValue: "Popover content",
        supportsTemplates: true,
      },
    ],
  },

  // ========== Dados (7) ==========
  {
    componentType: "Table",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 12,
    defaultRowSpan: 4,
    propFields: [],
  },
  {
    componentType: "Accordion",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 3,
    propFields: [],
  },
  {
    componentType: "Tabs",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 3,
    propFields: [],
  },
  {
    componentType: "Breadcrumb",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Pagination",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Avatar",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 1,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Calendar",
    category: "Dados",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 4,
    propFields: [],
  },

  // ========== Especializados (6) ==========
  {
    componentType: "Form",
    category: "Especializados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 4,
    propFields: [],
  },
  {
    componentType: "NavigationMenu",
    category: "Especializados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Sidebar",
    category: "Especializados",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 6,
    propFields: [],
  },
  {
    componentType: "Resizable",
    category: "Especializados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 3,
    propFields: [],
  },
  {
    componentType: "InputOTP",
    category: "Especializados",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Chart",
    category: "Especializados",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 4,
    propFields: [],
  },

  // ========== Utilitários (12) ==========
  {
    componentType: "Label",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "children",
        label: "Texto",
        type: "text",
        defaultValue: "Label",
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "AlertDialog",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Separator",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "ContextMenu",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "ScrollArea",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 4,
    propFields: [],
  },
  {
    componentType: "AspectRatio",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 3,
    propFields: [],
  },
  {
    componentType: "Command",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 3,
    propFields: [],
  },
  {
    componentType: "Collapsible",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 2,
    propFields: [],
  },
  {
    componentType: "Menubar",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 6,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "Slider",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 4,
    defaultRowSpan: 1,
    propFields: [
      {
        name: "value",
        label: "Valor",
        type: "number",
        defaultValue: 50,
        supportsTemplates: true,
      },
    ],
  },
  {
    componentType: "Switch",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 2,
    defaultRowSpan: 1,
    propFields: [],
  },
  {
    componentType: "RadioGroupUtil",
    category: "Utilitários",
    icon: "Square",
    defaultColSpan: 3,
    defaultRowSpan: 2,
    propFields: [],
  },
];

// Helper to get components by category
export const COMPONENT_CATEGORIES: Record<ComponentCategory, ComponentMetadata[]> = {
  Entrada: COMPONENT_CATALOG.filter((c) => c.category === "Entrada"),
  Seleção: COMPONENT_CATALOG.filter((c) => c.category === "Seleção"),
  Feedback: COMPONENT_CATALOG.filter((c) => c.category === "Feedback"),
  Layouts: COMPONENT_CATALOG.filter((c) => c.category === "Layouts"),
  Dados: COMPONENT_CATALOG.filter((c) => c.category === "Dados"),
  Especializados: COMPONENT_CATALOG.filter((c) => c.category === "Especializados"),
  Utilitários: COMPONENT_CATALOG.filter((c) => c.category === "Utilitários"),
};
