export const DEFAULT_MAX_TOKEN_BUDGET = 100000
export const DEFAULT_TOKEN_SAFETY_MARGIN = 0.8
export const DEFAULT_MAX_FILES_PER_TASK = 10
export const DEFAULT_ALLOW_SOFT_GATES = true

export const THRESHOLDS = {
  MAX_TOKEN_BUDGET: DEFAULT_MAX_TOKEN_BUDGET,
  TOKEN_SAFETY_MARGIN: DEFAULT_TOKEN_SAFETY_MARGIN,
  MAX_FILES_PER_TASK: DEFAULT_MAX_FILES_PER_TASK,
  ALLOW_SOFT_GATES: DEFAULT_ALLOW_SOFT_GATES,
}
